Feature/operator component
marroq/react-calculator pull request #2
Opened 2021-02-08 03:59 UTC by marroq

Component to save the information to resolve before clic on equal button

2021-02-08 18:19 UTC, baquiax requested changes

2021-02-08 18:19 UTC, baquiax commented on src/App.jsx
> +      <Operator
This `Operator` should have less responsibilities,  e.g only action as `+` or `-` and its unique responsibility should be notify to its parent that something was pressed

2021-02-09 15:40 UTC, baquiax approved these changes

2021-02-09 15:54 UTC, marroq commented on src/components/SumOperator/index.jsx
>          </button>
@baquiax 
Do you mean this, that the operator did the specific action of sum?

I was thinking in use the Operator component to show the operators and the array to acumulate the whole operation (operands and operators) to avoid create a component for each operator and resolve the arrays with the whole operation in other component, and the same with the Number component, every time you click an operator, the value of Number is saved and start again since 0.

Do you think I can do the same but with more components not to have many responsibilities in a component?, or what do you recommend me to do.

2021-02-09 15:58 UTC, baquiax commented on src/components/SumOperator/index.jsx
>          </button>
I was thinking in something like
```
<Operator operator="+" onClick={() => { (operator) => { setCurrentOperator(operator)} }}/>
<Operator operator="-" onClick={() => { (operator) => { setCurrentOperator(operator)} }}/>
<Operator operator="*" onClick={() => { (operator) => { setCurrentOperator(operator)} }}/>
<Operator operator="/" onClick={() => { (operator) => { setCurrentOperator(operator)} }}/>
```

Then the parent will catch the event and decided what to do with the operator chosen.

2021-02-10 03:32 UTC, marroq commented on src/components/SumOperator/index.jsx
>          </button>
Nice, I will take that recommendation

2021-02-10 03:32 UTC, merged